(function () {
  "use strict";
  var modules = [
    {icon:"▥",accent:"blue",title:"Sprzedaż i marża",subtitle:"Wynik, struktura i rentowność",summary:"Widok pokazujący nie tylko poziom sprzedaży, lecz także jakość przychodu i źródła wypracowanej marży.",information:["sprzedaż i marża w czasie","realizacja planu oraz zmiana rok do roku","struktura produktu, rynku lub kanału","największe wzrosty i spadki"],questions:["Co naprawdę napędza wynik?","Gdzie wzrost sprzedaży nie przekłada się na marżę?","Które odchylenia wymagają reakcji?"],decisions:"Priorytety handlowe, polityka cenowa, miks sprzedaży i koncentracja zasobów."},
    {icon:"◎",accent:"violet",title:"Plan a wykonanie",subtitle:"Odchylenia i odpowiedzialność",summary:"Kontrola realizacji budżetu z koncentracją na przyczynach odchyleń, a nie wyłącznie na ich wartości.",information:["wynik rzeczywisty, plan i prognoza","odchylenia wartościowe i procentowe","wpływ ceny, wolumenu i kosztu","obszary wymagające komentarza"],questions:["Dlaczego wynik różni się od planu?","Czy odchylenie jest trwałe czy jednorazowe?","Kto i kiedy podejmuje działanie?"],decisions:"Korekta działań, przesunięcia budżetu, aktualizacja celów i rozmowa o odpowiedzialności."},
    {icon:"◒",accent:"teal",title:"Płynność i gotówka",subtitle:"Wpływy, wydatki i prognoza",summary:"Praktyczne spojrzenie na gotówkę, które pozwala wcześniej zauważyć ryzyko i świadomie planować zobowiązania.",information:["stan i prognoza środków pieniężnych","oczekiwane wpływy i wydatki","należności i zobowiązania według terminów","minimalny bezpieczny poziom gotówki"],questions:["Kiedy może pojawić się luka płynnościowa?","Które wpływy są zagrożone?","Jakie wydatki można przesunąć bez szkody?"],decisions:"Terminy płatności, finansowanie, priorytety wydatków i działania windykacyjne."},
    {icon:"◇",accent:"green",title:"Kapitał obrotowy",subtitle:"Zapasy, należności, zobowiązania",summary:"Informacja o środkach zamrożonych w działalności operacyjnej i możliwościach ich bezpiecznego uwolnienia.",information:["rotacja zapasów, należności i zobowiązań","wiekowanie oraz pozycje przeterminowane","zapasy wolno rotujące i nadmiarowe","cykl konwersji gotówki"],questions:["Gdzie zamrożona jest gotówka?","Co pogarsza cykl kapitału obrotowego?","Które pozycje wymagają konkretnego właściciela?"],decisions:"Poziom zapasu, warunki handlowe, windykacja i negocjacje z dostawcami."},
    {icon:"≋",accent:"orange",title:"Koszty i efektywność",subtitle:"Struktura, trendy i źródła zmian",summary:"Obraz kosztów powiązany z działalnością operacyjną, pozwalający odróżnić oszczędność od pozornego cięcia.",information:["koszty według rodzaju, miejsca i procesu","koszt jednostkowy i jego składowe","koszty stałe oraz zmienne","trend, plan i istotne odchylenia"],questions:["Które koszty rosną szybciej niż skala biznesu?","Co jest przyczyną zmiany kosztu jednostkowego?","Gdzie działanie poprawi efektywność bez utraty jakości?"],decisions:"Programy poprawy efektywności, priorytety zakupowe, wykorzystanie zasobów i kalkulacje cen."},
    {icon:"↗",accent:"pink",title:"Prognoza",subtitle:"Scenariusze i spojrzenie w przód",summary:"Aktualizowana prognoza wyniku i gotówki, która pokazuje możliwe warianty zamiast jednego pozornie pewnego planu.",information:["prognoza krocząca wyniku i gotówki","scenariusz bazowy, ostrożny i ambitny","kluczowe założenia oraz ich wrażliwość","sygnały wczesnego ostrzegania"],questions:["Co zmieniło się od ostatniej prognozy?","Które założenia mają największy wpływ?","Jak wygląda wynik w niekorzystnym scenariuszu?"],decisions:"Tempo inwestycji, zabezpieczenie płynności, cele operacyjne i działania wyprzedzające."},
    {icon:"⌁",accent:"red",title:"Panel zarządczy",subtitle:"Najważniejsze KPI w jednym miejscu",summary:"Syntetyczny obraz kondycji organizacji łączący wynik finansowy, operacje, gotówkę i perspektywę przyszłości.",information:["kluczowe wskaźniki finansowe i operacyjne","status celów i inicjatyw","najważniejsze ryzyka oraz szanse","komentarze właścicieli obszarów"],questions:["Co dziś wymaga uwagi zarządu?","Czy realizujemy cele i co nam przeszkadza?","Jakie trzy decyzje mają teraz największe znaczenie?"],decisions:"Priorytety organizacji, alokacja zasobów, reakcja na ryzyka i komunikacja zarządcza."},
    {icon:"⊙",accent:"gold",title:"Ryzyka i działania",subtitle:"Od sygnału do odpowiedzialności",summary:"Rejestr istotnych ryzyk i działań, który łączy wskaźniki ostrzegawcze z właścicielem oraz terminem reakcji.",information:["ryzyko, prawdopodobieństwo i możliwy wpływ","wskaźniki wczesnego ostrzegania","plan reakcji i osoba odpowiedzialna","status oraz termin działania"],questions:["Co może zagrozić realizacji celów?","Po czym wcześniej poznamy, że ryzyko rośnie?","Czy działanie ma właściciela i termin?"],decisions:"Działania zabezpieczające, eskalacja problemów, akceptacja ryzyka i monitoring realizacji."}
  ];
  var grid=document.getElementById("tool-grid"),detail=document.getElementById("detail");
  function list(items){return items.map(function(item){return "<li>"+item+"</li>";}).join("");}
  modules.forEach(function(module,index){var button=document.createElement("button");button.type="button";button.className="tool-card tool-card--"+module.accent;button.setAttribute("aria-controls","detail");button.setAttribute("aria-expanded","false");button.innerHTML='<span class="tool-icon" aria-hidden="true">'+module.icon+'</span><span class="tool-title">'+module.title+'</span><span class="tool-subtitle">'+module.subtitle+'</span><span class="tool-open">Zobacz zakres <span aria-hidden="true">→</span></span>';button.addEventListener("click",function(){showModule(module,button);});grid.appendChild(button);});
  function showModule(module,activeButton){grid.querySelectorAll(".tool-card").forEach(function(button){var active=button===activeButton;button.classList.toggle("is-active",active);button.setAttribute("aria-expanded",active?"true":"false");});var icon=document.getElementById("detail-icon");icon.textContent=module.icon;icon.className="detail-icon detail-icon--"+module.accent;document.getElementById("detail-kicker").textContent="Przykładowy zakres modułu";document.getElementById("detail-title").textContent=module.title;document.getElementById("detail-summary").textContent=module.summary;document.getElementById("detail-information").innerHTML=list(module.information);document.getElementById("detail-questions").innerHTML=list(module.questions);document.getElementById("detail-decisions").textContent=module.decisions;detail.hidden=false;detail.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});}
  document.getElementById("detail-close").addEventListener("click",function(){detail.hidden=true;grid.querySelectorAll(".tool-card").forEach(function(button){button.classList.remove("is-active");button.setAttribute("aria-expanded","false");});});
})();
